console.log('number' + 23 + 32);

console.log(41 + 1 + 'number');

console.log(null + 1);

console.log('five' + + 'two');

console.log(2 && 7);

console.log(+'40' + +'2');

console.log('10' - 5 === 6);

console.log(true + false);

console.log('4px' - 3);

console.log('4' - 3);

console.log('2' + 3 ** 2);

console.log(12 / '6');

console.log(23 + 42 + 'number');

console.log('10' + (5 === 6));

console.log('number' + 15 + 3);